#pragma once
#ifndef AUTOGENERATED_H
#define AUTOGENERATED_H

#define select_0(channel1, true, message1) \
{ \
if (true) \
{ \
if (true) \
{ \
if (channel1.read(&message1, false)) \
{ \
                { \
                    printf("1"); \
                } \
break;\
} \
} \
else \
{ \
if (channel1.write(message1, false)) \
{ \
                { \
                    printf("1"); \
                } \
break;\
} \
} \
                { \
                    print("Nothing"); \
                } \
} \
}


// =========================== END AUTOGENERATED SOURCE CODE ==================================

#endif
