#include <iostream>
#include <mpi.h>
#include "include/DistributedRuntime.h"




#include "AUTOGENERATED.h"


// Ran with:  mpirun  --oversubscribe -np 2 example1


int main(int argc, char* argv[]) {
    DistributedRuntime::DistributedChannelUnbounded<int> channel1(2);
    DistributedRuntime::run();
    if(MPIUtils::getCurrentProc() == 0){
        int message2;

select_0(channel1, true, message1);

    } else{
        int message1 = 1;
channel1.write(message1, false);
    }
    return 0;

}
